import com.github.jengelman.gradle.plugins.shadow.tasks.ShadowJar

plugins {
    kotlin("jvm") version "1.9.25"
    id("com.github.johnrengelman.shadow") version "8.1.1"
    application
}

group = "com.trika"
version = "0.1.0"

repositories {
    mavenCentral()
}

dependencies {
    // sherpa-onnx native-lib jar (macOS arm64 dylibs bundled inside).
    // The build script (sherpa_onnx_build.sh) downloads this jar into
    // libs/ before invoking gradle. The Kotlin API source is vendored
    // under src/main/kotlin/com/k2fsa/sherpa/onnx/.
    //
    // This file dependency is optional — compilation succeeds without it
    // (the API classes are vendored source). The jar is only needed at
    // runtime for the native JNI symbols.
    if (file("libs/sherpa-onnx-native-lib-osx-aarch64.jar").exists()) {
        runtimeOnly(files("libs/sherpa-onnx-native-lib-osx-aarch64.jar"))
    }
}

application {
    mainClass.set("com.trika.sherpaonnxstt.MainKt")
    // java.library.path is injected by the wrapper script generated by
    // the installDist task (see sherpa_onnx_build.sh which patches the
    // generated start script's DEFAULT_JVM_OPTS).
}

kotlin {
    jvmToolchain(17)
}

tasks.withType<ShadowJar> {
    archiveBaseName.set("SherpaOnnxSTT")
    archiveClassifier.set("")
    archiveVersion.set("")
    manifest {
        attributes["Main-Class"] = "com.trika.sherpaonnxstt.MainKt"
    }
}

tasks.named("build") {
    dependsOn(tasks.named("shadowJar"))
}

// Convenience task: run the CLI with arguments passed via -Pargs="..."
// e.g.: ./gradlew runCli -Pargs="--file /path/to/audio.wav"
tasks.register<JavaExec>("runCli") {
    classpath = sourceSets.main.get().runtimeClasspath
    mainClass.set("com.trika.sherpaonnxstt.MainKt")
    val rawArgs = project.findProperty("args") as String? ?: ""
    if (rawArgs.isNotBlank()) {
        args = rawArgs.split(" ")
    }
    // Native library path — set by build script before invoking gradle.
    val libPath = project.findProperty("nativeLibPath") as String? ?: ""
    if (libPath.isNotBlank()) {
        systemProperty("java.library.path", libPath)
    }
}
