DO $$
DECLARE
    role_permissions JSONB := '{
        "SUPER_ADMIN": [
            "DEPARTMENT_CREATE", "DEPARTMENT_EDIT", "DEPARTMENT_LIST", "DEPARTMENT_DOWNLOAD",
            "SUBDEPARTMENT_LIST", "SUBDEPARTMENT_DOWNLOAD",
            "USER_LIST", "USER_CREATE", "USER_EDIT", "USER_PASSWORD_RESET", "USER_DELETE", "USER_DOWNLOAD"
        ],
        "DEPT_ADMIN": [
            "SUBDEPARTMENT_CREATE", "SUBDEPARTMENT_EDIT", "SUBDEPARTMENT_LIST", "SUBDEPARTMENT_DOWNLOAD",
            "USER_CREATE", "USER_EDIT", "USER_PASSWORD_RESET", "USER_DELETE", "USER_LIST", "USER_DOWNLOAD"
        ],
        "SUBDEPT_ADMIN": [
            "USER_CREATE", "USER_EDIT", "USER_PASSWORD_RESET", "USER_DELETE", "USER_LIST", "USER_DOWNLOAD",
            "CHECKSHEET_MANAGEMENT_LIST", "CHECKSHEET_MANAGEMENT_DETAIL_CREATE",
            "CHECKSHEET_MANAGEMENT_DETAIL_EDIT", "CHECKSHEET_MANAGEMENT_DETAIL_VIEW", "CHECKSHEET_MANAGEMENT_TEMPLATE_VIEW",
            "CHECKSHEET_MANAGEMENT_CONTENT_VIEW", "CHECKSHEET_MANAGEMENT_VALIDATOR_COMMENT_VIEW", "CHECKSHEET_MANAGEMENT_APPROVER_COMMENT_VIEW",
            "CHECKSHEET_LISTING", "CHECKSHEET_DATA_VALIDATOR_COMMENT_VIEW", "CHECKSHEET_DATA_APPROVER_COMMENT_VIEW"
        ],
        "CHK_SHT_PREPARE": [
            "CHECKSHEET_MANAGEMENT_LIST", "CHECKSHEET_MANAGEMENT_DETAIL_VIEW",
            "CHECKSHEET_MANAGEMENT_TEMPLATE_CREATE", "CHECKSHEET_MANAGEMENT_TEMPLATE_EDIT", "CHECKSHEET_MANAGEMENT_TEMPLATE_VIEW",
            "CHECKSHEET_MANAGEMENT_CONTENT_VIEW", "CHECKSHEET_MANAGEMENT_VALIDATOR_COMMENT_VIEW",
            "CHECKSHEET_MANAGEMENT_APPROVER_COMMENT_VIEW", "CHECKSHEET_LISTING",
            "CHECKSHEET_DATA_VALIDATOR_COMMENT_VIEW", "CHECKSHEET_DATA_APPROVER_COMMENT_VIEW"
        ],
        "CHK_SHT_VALIDATOR": [
            "CHECKSHEET_MANAGEMENT_LIST", "CHECKSHEET_MANAGEMENT_DETAIL_VIEW",
            "CHECKSHEET_MANAGEMENT_TEMPLATE_VIEW", "CHECKSHEET_MANAGEMENT_CONTENT_VIEW",
            "CHECKSHEET_MANAGEMENT_VALIDATOR_COMMENT_CREATE", "CHECKSHEET_MANAGEMENT_VALIDATOR_COMMENT_EDIT",
            "CHECKSHEET_MANAGEMENT_VALIDATOR_COMMENT_VIEW", "CHECKSHEET_MANAGEMENT_APPROVER_COMMENT_VIEW",
            "CHECKSHEET_LISTING", "CHECKSHEET_DATA_VALIDATOR_COMMENT_VIEW", "CHECKSHEET_DATA_APPROVER_COMMENT_VIEW"
        ],
        "CHK_SHT_APPROVER": [
            "CHECKSHEET_MANAGEMENT_LIST", "CHECKSHEET_MANAGEMENT_DETAIL_VIEW",
            "CHECKSHEET_MANAGEMENT_TEMPLATE_VIEW", "CHECKSHEET_MANAGEMENT_CONTENT_VIEW",
            "CHECKSHEET_MANAGEMENT_VALIDATOR_COMMENT_VIEW", "CHECKSHEET_MANAGEMENT_APPROVER_COMMENT_VIEW",
            "CHECKSHEET_MANAGEMENT_APPROVER_COMMENT_CREATE", "CHECKSHEET_MANAGEMENT_APPROVER_COMMENT_EDIT",
            "CHECKSHEET_LISTING", "CHECKSHEET_DATA_VALIDATOR_COMMENT_VIEW", "CHECKSHEET_DATA_APPROVER_COMMENT_VIEW"
        ],
        "CHK_SHT_DATA_VALIDATOR": [
            "CHECKSHEET_LISTING", "CHECKSHEET_DATA_VALIDATOR_COMMENT_CREATE",
            "CHECKSHEET_DATA_VALIDATOR_COMMENT_EDIT", "CHECKSHEET_DATA_VALIDATOR_COMMENT_VIEW",
            "CHECKSHEET_DATA_APPROVER_COMMENT_VIEW", "NPD_CREATE"
        ],
        "CHK_SHT_DATA_APPROVER": [
            "CHECKSHEET_LISTING", "CHECKSHEET_DATA_VALIDATOR_COMMENT_VIEW",
            "CHECKSHEET_DATA_APPROVER_COMMENT_CREATE", "CHECKSHEET_DATA_APPROVER_COMMENT_EDIT",
            "CHECKSHEET_DATA_APPROVER_COMMENT_VIEW"
        ],
        "OPERATOR": [
            "CHECKSHEET_FILL_LISTING", "CHECKSHEET_FILL_CHECKSHEET_DETAIL", "CHECKSHEET_FILL_ANSWER"
        ]
    }';
    role_code_key TEXT;
    permission_code_key TEXT;
    permission_name TEXT;
BEGIN
    FOR role_code_key IN SELECT jsonb_object_keys(role_permissions)
    LOOP
        FOR permission_code_key IN SELECT jsonb_array_elements_text(role_permissions -> role_code_key)
        LOOP
            permission_name := initcap(replace(permission_code_key, '_', ' '));

            INSERT INTO permissions (permission_code, name, description)
            VALUES (permission_code_key, permission_name, permission_name)
            ON CONFLICT (permission_code) DO NOTHING;

            INSERT INTO role_permissions (role_id, permission_id, created_at)
            SELECT r.id, p.id, COALESCE(p.created_at, CURRENT_TIMESTAMP)
            FROM roles r
            JOIN permissions p ON p.permission_code = permission_code_key
            WHERE r.role_code = role_code_key
            ON CONFLICT (role_id, permission_id) DO NOTHING;
        END LOOP;
    END LOOP;
END $$;