#!/usr/bin/env bash
#
# Build the SherpaOnnxSTT JVM CLI and print the resulting fat-jar path.
#
# What this script does:
#   1. Detects the macOS architecture (arm64 or x86_64).
#   2. Downloads the sherpa-onnx native-lib jar for the current arch from
#      GitHub Releases into SherpaOnnxSTT/libs/ (skipped if already present).
#   3. Extracts the JNI dylibs from the native-lib jar into
#      SherpaOnnxSTT/build/native-libs/ so java.library.path can find them.
#   4. Builds SherpaOnnxSTT with Gradle (shadow fat-jar).
#   5. Generates a wrapper script at
#      SherpaOnnxSTT/build/install/SherpaOnnxSTT/bin/SherpaOnnxSTT
#      that injects -Djava.library.path automatically.
#
# Usage:
#   ./sherpa_onnx_build.sh              -- release build (default)
#   ./sherpa_onnx_build.sh debug        -- debug / verbose Gradle output
#
# Output (last line of stdout):
#   Absolute path to the SherpaOnnxSTT wrapper script.
#   Callers can: BIN=$(./sherpa_onnx_build.sh | tail -1)
#
# Requirements:
#   - Java 17+ (JAVA_HOME or on PATH)
#   - curl
#   - jar (part of JDK, same JAVA_HOME)
#   - tar with bz2 support (standard on macOS)

set -euo pipefail

SHERPA_VERSION="1.13.2"
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PKG_DIR="$SCRIPT_DIR/SherpaOnnxSTT"
LIBS_DIR="$PKG_DIR/libs"
NATIVE_LIBS_DIR="$PKG_DIR/build/native-libs"
INSTALL_DIR="$PKG_DIR/build/install/SherpaOnnxSTT"

CONFIG="${1:-release}"
GRADLE_FLAGS=""
if [[ "$CONFIG" == "debug" ]]; then
  GRADLE_FLAGS="--info"
fi

# ---------------------------------------------------------------------------
# 1. Detect architecture
# ---------------------------------------------------------------------------
ARCH="$(uname -m)"
case "$ARCH" in
  arm64)   SHERPA_ARCH="osx-aarch64" ;;
  x86_64)  SHERPA_ARCH="osx-x64"     ;;
  *)
    echo "error: unsupported architecture: $ARCH (expected arm64 or x86_64)" >&2
    exit 2
    ;;
esac

NATIVE_JAR="sherpa-onnx-native-lib-${SHERPA_ARCH}-v${SHERPA_VERSION}.jar"
NATIVE_JAR_URL="https://github.com/k2-fsa/sherpa-onnx/releases/download/v${SHERPA_VERSION}/${NATIVE_JAR}"
NATIVE_JAR_PATH="$LIBS_DIR/${NATIVE_JAR%%-v*}.jar"  # canonical name without version tag

# ---------------------------------------------------------------------------
# 2. Download native-lib jar (skip if cached)
# ---------------------------------------------------------------------------
mkdir -p "$LIBS_DIR"

if [[ ! -f "$NATIVE_JAR_PATH" ]]; then
  echo "Downloading sherpa-onnx native lib ($SHERPA_ARCH) v${SHERPA_VERSION} …" >&2
  curl -fsSL --retry 3 "$NATIVE_JAR_URL" -o "$NATIVE_JAR_PATH"
  echo "  → saved to $NATIVE_JAR_PATH" >&2
else
  echo "Native lib already cached: $NATIVE_JAR_PATH" >&2
fi

# ---------------------------------------------------------------------------
# 3. Extract dylibs from the native-lib jar into build/native-libs/
# ---------------------------------------------------------------------------
mkdir -p "$NATIVE_LIBS_DIR"

JAR_CMD="${JAVA_HOME:+$JAVA_HOME/bin/}jar"

# Extract only the dylib files; strip the leading path components.
if ! ls "$NATIVE_LIBS_DIR"/*.dylib >/dev/null 2>&1; then
  echo "Extracting native dylibs from $NATIVE_JAR_PATH …" >&2
  TMP_EXTRACT="$(mktemp -d)"
  trap 'rm -rf "$TMP_EXTRACT"' EXIT

  (cd "$TMP_EXTRACT" && "$JAR_CMD" xf "$NATIVE_JAR_PATH")

  find "$TMP_EXTRACT" -name "*.dylib" -exec cp -f {} "$NATIVE_LIBS_DIR/" \;
  echo "  → dylibs in $NATIVE_LIBS_DIR:" >&2
  ls "$NATIVE_LIBS_DIR/" >&2
fi

# ---------------------------------------------------------------------------
# 4. Build with Gradle
# ---------------------------------------------------------------------------
echo "Building SherpaOnnxSTT …" >&2
cd "$PKG_DIR"

# Symlink the native jar under its canonical name so build.gradle.kts finds it.
SYMLINK_NAME="sherpa-onnx-native-lib-osx-aarch64.jar"
if [[ ! -f "$LIBS_DIR/$SYMLINK_NAME" ]]; then
  ln -sf "$(basename "$NATIVE_JAR_PATH")" "$LIBS_DIR/$SYMLINK_NAME"
fi

# shellcheck disable=SC2086
./gradlew shadowJar installDist $GRADLE_FLAGS

# ---------------------------------------------------------------------------
# 5. Generate wrapper script with java.library.path injected
# ---------------------------------------------------------------------------
WRAPPER_SCRIPT="$INSTALL_DIR/bin/SherpaOnnxSTT"
mkdir -p "$INSTALL_DIR/bin"
mkdir -p "$INSTALL_DIR/lib"

FAT_JAR="$PKG_DIR/build/libs/SherpaOnnxSTT.jar"
if [[ ! -f "$FAT_JAR" ]]; then
  echo "error: fat jar not found at $FAT_JAR after build" >&2
  exit 3
fi

# Copy jar alongside wrapper.
cp -f "$FAT_JAR" "$INSTALL_DIR/lib/SherpaOnnxSTT.jar"

cat > "$WRAPPER_SCRIPT" <<'WRAPPER_EOF'
#!/usr/bin/env bash
# SherpaOnnxSTT wrapper — injects java.library.path for sherpa-onnx JNI.
# Generated by sherpa_onnx_build.sh — do not edit by hand.
set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
NATIVE_LIBS="$(cd "$SCRIPT_DIR/../../.." && pwd)/native-libs"
JAR="$SCRIPT_DIR/../lib/SherpaOnnxSTT.jar"

if [[ ! -f "$JAR" ]]; then
  echo "SherpaOnnxSTT error: jar not found at $JAR" >&2
  exit 1
fi

exec java \
  -Djava.library.path="$NATIVE_LIBS" \
  -jar "$JAR" \
  "$@"
WRAPPER_EOF

chmod +x "$WRAPPER_SCRIPT"

echo >&2 ""
echo >&2 "Build complete."
echo >&2 "  Fat-jar:        $FAT_JAR"
echo >&2 "  Wrapper script: $WRAPPER_SCRIPT"
echo >&2 ""
echo >&2 "Usage:"
echo >&2 "  $WRAPPER_SCRIPT --file /path/to/audio.wav"

# Last line = binary path (for callers using tail -1)
echo "$WRAPPER_SCRIPT"
