spring.datasource.driver-class-name=org.postgresql.Driver
#spring.datasource.url = jdbc:postgresql://13.126.238.240:5432/smartcomply
spring.datasource.url = jdbc:postgresql://172.31.0.157:5432/smartcomply
spring.datasource.username = dilipv
spring.datasource.password = W@1zQJ66#X7
spring.jpa.properties.hibernate.default_schema=public

#management.port = 9000
server.port = 8089
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
#jwt
application.security.jwt.expiration=10000000
application.security.jwt.refresh-token.expiration=100000000

app.jwtRefreshTokenExpiration=200000000
app.jwtTokenExpiration=100000
app.otpExpiration=300

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.current_session_context_class=org.springframework.orm.hibernate5.SpringSessionContext

# Flyway Configuration
spring.flyway.enabled=true
spring.flyway.url=${spring.datasource.url}
spring.flyway.user=${spring.datasource.username}
spring.flyway.password=${spring.datasource.password}
spring.flyway.schemas=${spring.jpa.properties.hibernate.default_schema}
spring.flyway.baseline-on-migrate=true
spring.flyway.baseline-version=1
spring.flyway.locations=classpath:db/migration
#spring.flyway.locations=classpath:db/migration,filesystem:/opt/migration
spring.flyway.validate-on-migrate=false

spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true
logging.level.org.apache.coyote=DEBUG
#================================
# Mail Configuration value
#================================
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=tipl.rnaipl@gmail.com
spring.mail.password=kczceimfgtyxhudv
spring.mail.properties.mail.smtp.auth=false
spring.mail.properties.mail.smtp.starttls.enable=true

 
audit.mail.cc.user=
audit.mail.bcc.user=

#================================
# AWS S3 configuration
#================================

aws.access_key_id=AKIAWZPKMOG5Z7LYSY7H
aws.secret_access_key=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
aws.s3.bucket=comply-genix/smartcomply
aws.s3.region=ap-south-1
spring.jpa.database-platform=org.hibernate.dialect.MySQL5Dialect
#==========================================================================
# File Storage Properties
# All files uploaded through the REST API will be stored in this directory
#==========================================================================
file.uploadDir=/SMARTCOMPLY/
app.protocol=https

is_email_send=true
is_notification_send=true

is_API_log_save=true


spring.http.multipart.max-file-size=10000MB
spring.http.multipart.max-request-size=100000MB

spring.servlet.multipart.max-file-size=1000MB
spring.servlet.multipart.max-request-size=1000MB
app.environmentDomain=https://smartcomply.tiez.net