"""SherpaOnnx strategy.

Wraps the SherpaOnnxSTT Kotlin/JVM CLI (see
voice-engine/native/android/SherpaOnnxSTT) via subprocess and streams JSONL
transcript events back into the lab as ``TranscriptEvent`` objects.

The JVM CLI uses sherpa-onnx's OfflineRecognizer with Whisper-tiny-en ONNX
models. This is the **same sherpa-onnx library** that will power the Android
production path — the JVM target is used here for macOS lab evaluation without
requiring an Android device or emulator.

Binary discovery:
    - Default: the wrapper script generated by the build at
      ``voice-engine/native/android/SherpaOnnxSTT/build/install/SherpaOnnxSTT/bin/SherpaOnnxSTT``
      relative to the repo root.
    - Override with the ``SHERPA_ONNX_BIN`` environment variable.

Model selection:
    - Default: ``whisper-tiny-en`` (the only model supported in v0.1).
    - Override per-instance via the ``model`` constructor argument or globally
      via the ``SHERPA_ONNX_MODEL`` environment variable.

Build the CLI first:
    voice-engine/native/android/sherpa_onnx_build.sh

Partials note:
    sherpa-onnx OfflineRecognizer does not stream intermediate tokens; it
    returns one result per segment after decoding is complete. The CLI
    simulates one ``partial`` event per segment (first-word preview) for
    JSONL contract compatibility. The ``engine_metadata.simulated`` field is
    ``true`` on simulated partials.

JSON event schema (identical to WhisperKitSTT):
    {
      "type": "partial" | "final",
      "text": "...",
      "timestamp_ms": <int>,
      "latency_ms_from_audio_start": <int>,
      "confidence": <float> | null,
      "engine_metadata": {
          "engine": "sherpa_onnx",
          "model": "whisper-tiny-en",
          "is_volatile": <bool>,
          ...
      }
    }
"""

from __future__ import annotations

import json
import os
import shutil
import subprocess
from pathlib import Path
from typing import Iterable, Iterator

from voice_lab.strategies.base import TranscriptionStrategy
from voice_lab.strategies.whisperkit import _event_from_json, _terminate
from voice_lab.types import TranscriptEvent, TranscriptionError


# Repo-anchored default binary location. Resolved from this file's location
# so the path is correct regardless of CWD.
#
# This file lives at:
#   voice-engine/lab/src/voice_lab/strategies/sherpa_onnx.py
# We want:
#   voice-engine/native/android/SherpaOnnxSTT/build/install/SherpaOnnxSTT/bin/SherpaOnnxSTT
# which is parents[4]/native/android/SherpaOnnxSTT/build/install/SherpaOnnxSTT/bin/SherpaOnnxSTT
_DEFAULT_BIN = (
    Path(__file__).resolve().parents[4]
    / "native"
    / "android"
    / "SherpaOnnxSTT"
    / "build"
    / "install"
    / "SherpaOnnxSTT"
    / "bin"
    / "SherpaOnnxSTT"
)

_DEFAULT_MODEL = "whisper-tiny-en"


def _resolve_binary() -> Path:
    """Return the SherpaOnnxSTT binary path, honoring SHERPA_ONNX_BIN if set."""
    override = os.environ.get("SHERPA_ONNX_BIN")
    if override:
        return Path(override).expanduser()
    return _DEFAULT_BIN


def _resolve_model() -> str:
    """Return the sherpa-onnx model name, honoring SHERPA_ONNX_MODEL if set."""
    override = os.environ.get("SHERPA_ONNX_MODEL")
    if override:
        return override
    return _DEFAULT_MODEL


class SherpaOnnxStrategy(TranscriptionStrategy):
    """sherpa-onnx (Whisper ONNX) strategy — JVM CLI wrapping OfflineRecognizer."""

    name = "sherpa_onnx"

    def __init__(
        self,
        *,
        binary_path: Path | None = None,
        model: str | None = None,
        partials: bool = True,
    ) -> None:
        self._binary_path = Path(binary_path) if binary_path else None
        self._model = model
        self._partials = partials

    def _build_argv(self, binary: Path, audio_path: Path) -> list[str]:
        model = self._model or _resolve_model()
        return [
            str(binary),
            "--file",
            str(audio_path),
            "--model",
            model,
            "--partials",
            "true" if self._partials else "false",
        ]

    def transcribe(self, audio_path: Path) -> Iterable[TranscriptEvent]:
        """Yield TranscriptEvents in audio-time order.

        Streams stdout from the SherpaOnnxSTT subprocess line-by-line; one
        JSON event per line. Backpressure is handled by the caller iterating
        lazily.
        """
        return _run_sherpa_onnx_stt(
            argv_builder=lambda bin_path: self._build_argv(bin_path, audio_path),
            binary_path=self._binary_path,
            audio_path=audio_path,
            engine_label=self.name,
        )


# ---------------------------------------------------------------------------
# Subprocess plumbing
# ---------------------------------------------------------------------------


def _run_sherpa_onnx_stt(
    *,
    argv_builder,
    binary_path: Path | None,
    audio_path: Path,
    engine_label: str,
) -> Iterator[TranscriptEvent]:
    """Spawn SherpaOnnxSTT, stream JSONL stdout, yield TranscriptEvent.

    Lazy — does not buffer full stdout. Raises TranscriptionError on any
    failure with a fix-it hint.
    """
    audio_path = Path(audio_path)
    if not audio_path.exists():
        raise TranscriptionError(
            f"audio file not found: {audio_path}. "
            "Pass an existing path to transcribe()."
        )

    binary = Path(binary_path) if binary_path else _resolve_binary()
    if not binary.exists() or not os.access(binary, os.X_OK):
        java_present = shutil.which("java") is not None
        if java_present:
            hint = (
                "Build the JVM CLI first:  "
                "voice-engine/native/android/sherpa_onnx_build.sh"
            )
        else:
            hint = (
                "Install Java 17+ and then run "
                "voice-engine/native/android/sherpa_onnx_build.sh"
            )
        raise TranscriptionError(
            f"{engine_label}: SherpaOnnxSTT binary not found or not "
            f"executable at {binary}. {hint}. You can also set SHERPA_ONNX_BIN "
            "to point at an alternate location."
        )

    argv = argv_builder(binary)

    try:
        proc = subprocess.Popen(
            argv,
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
            bufsize=1,  # line-buffered
            text=True,
            encoding="utf-8",
        )
    except OSError as e:
        raise TranscriptionError(
            f"{engine_label}: failed to spawn SherpaOnnxSTT subprocess "
            f"({binary}): {e}"
        ) from e

    assert proc.stdout is not None
    assert proc.stderr is not None

    try:
        for line in proc.stdout:
            line = line.strip()
            if not line:
                continue
            try:
                raw = json.loads(line)
            except json.JSONDecodeError as e:
                _terminate(proc)
                raise TranscriptionError(
                    f"{engine_label}: failed to parse SherpaOnnxSTT JSON "
                    f"event ({e}): {line!r}"
                ) from e

            # Reuse WhisperKit's _event_from_json — same JSONL schema.
            yield _event_from_json(raw)
    finally:
        stderr_text = ""
        try:
            stderr_text = proc.stderr.read() or ""
        except Exception:
            pass
        rc = proc.wait()
        if rc not in (0,):
            raise TranscriptionError(
                f"{engine_label}: SherpaOnnxSTT exited with code {rc}. "
                f"stderr: {stderr_text.strip() or '<empty>'}"
            )
